### ISSUE TITLE
Returns 500 - need help diagnosing

### ISSUE THREAD

**Issue by tim-massey** [eelzon/morgenbot#8]
I keep getting the following error

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

Any clues on how to diagnose this error? This is on heroku and locally.

**Comment by frodopwns** [comment]
I too am getting a 500 for the !standup command.  !help and !start seem to return a 200.

**Comment by frodopwns** [comment]
127.0.0.1 - - [24/Apr/2015 13:34:02] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response

**Comment by frodopwns** [comment]
If you don't set ignore_users things go awry:

IGNORE_USERS: a string representing a comma-separated array of strings representing active channel users who never stand up. (eg '["username1", "username2"]'; optional; defaults to '')

```
ignore_users = os.environ['IGNORE_USERS'] if 'IGNORE_USERS' in os.environ.keys() else ''

ignore_users_array = eval(ignore_users)
```
eval('') causes
```
File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing
```

**Comment by frodopwns** [comment]
@tim-massey try this change https://github.com/frodopwns/morgenbot/commit/d4b648004824723b4cb5a782f6f6bf4fc73fed31

**Comment by eelzon** [comment]
Thank you for reporting this bug @tim-massey, and thanks for the pull request, @frodopwns!
